n:n relation ready
IIC2143/Proyecto-Ejemplo pull request #5
Opened 2022-10-03 18:07 UTC by kunafuego

#  Ayudantía A + M

## Description

Se agregó una relación n:n a nivel de código. Se creó una jointable llamada games_users en la que aparecerán los pares (usuario, juego), tal que el usuario tiene a ese juego dentro de sus favoritos. Para agregar o eliminar favoritos, se agregó un button_to desde el index de los games.

### ¿Qué se agregó?

Cada usuario puede agregar y desagregar juegos a favoritos.

### ¿Cómo se hizo?

Primero se hizo la migración correspondiente, se agregaron los métodos en el controlador de games, se crearon rutas con resources y members para cada método creado y se agregó código en la view del index de los juegos para agregar y desagregar juegos a favoritos.

## Requerimientos

Correr las migraciones

## Cambios adicionales

Ni uno.

2022-10-03 18:10 UTC, meretamal approved these changes
Notables cambios @kunafuego, solo tengo unos pequeños comentarios

2022-10-03 18:10 UTC, meretamal commented on app/views/games/index.html.erb
> +        <td> <%= button_to "Eliminar de favoritos", unfavorite_game_path(game.id), method: :delete %> </td>
Se podría traducir al inglés para mantener consistencia con el resto de la app

2022-10-03 18:10 UTC, meretamal commented on app/views/games/index.html.erb
> +        <td> <%= button_to "Agregar a favoritos", favorite_game_path(game.id)%> </td>
IDEM

2022-10-04 01:16 UTC, vicentethomas submitted a review, later dismissed

2022-10-06 03:23 UTC, Vinuelax submitted a review, later dismissed

2022-10-06 11:14 UTC, meretamal requested changes
Notables cambios, solo tengo un pequeño comentario

2022-10-06 11:14 UTC, meretamal commented on config/routes.rb
> +  delete '/reviews/:id', to: 'reviews#delete', as: 'reviews_delete'
Usaría `nested routes` con `resources` para manejar las rutas

2022-10-12 10:53 UTC, merged